#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require sqlfluff
sqlfluff fix --dialect sqlite --ignore parsing -- *.sql
rm -f lint.out
sqlfluff lint --dialect sqlite --ignore parsing -- *.sql &> lint.out
declare -i exitcode=$?
if [[ $exitcode != 0 ]]; then
  echo "Errors found. Check lint.out"
fi
exit "$exitcode"
